Avoid reporting to summary
netlify/netlify-plugin-edge-handlers pull request #92
Opened 2020-10-05 15:20 UTC by nasivuela

**Which problem is this pull request solving?**

- Having a core plugin reporting to the summary which increases confusion mentioned on https://github.com/netlify/pod-the-builder/issues/68
- [Watch logs] link leads to 404 on public deploys because edge handlers logs aren't public.

**List other issues or pull requests related to this problem**
https://github.com/netlify/netlify-react-ui/pull/5934 will add the link on the hero

**Describe alternatives you've considered**
Leave it as it is, but 🙅🏽‍♀️

**Checklist**

- [ ] The status checks are successful (continuous integration). Those can be seen below.

2020-10-05 15:26 UTC, nasivuela commented
I looked at https://github.com/netlify/netlify-plugin-edge-handlers/pull/85 to revert the changes and run the test locally. Let me know if there is something else I should do to verify I'm not breaking things.

2020-10-05 15:30 UTC, mraerino requested changes
i want to keep this ability for now.
there is no clear loss by having it. the "wrong icon" situation doesn't justify getting rid of this imho.

it will only show up for early access customers so not a huge chance to confuse anyone.

we also report in the summary if you deployed functions.

2020-10-05 15:53 UTC, nasivuela commented
@mraerino functions do not output to a dedicated row, there are only listed in the info row! And that's a behavior we want to improve to bring clarity, instead of making it more prominent as it is.

I can see there was an agreement on slack to revisit it after Jamstack and I'm ok with it. 
I can update the PR to only remove the buggy link, sounds good?

Finally, this makes me think that we need a process to be sure that if any of our core plugins adds a dedicated row to the summary, docs and design teams are involved. cc @iKristy @rstavchansky

2020-10-05 18:10 UTC, iKristy commented
Agree to re-visit after the private beta launch.

Just to re-clarify: if we are removing the link, then are we also removing the dedicated row as well? If the current pattern is to include the core-plugins in the total info row, then I would stick to this to maintain consistency with the functions core-plugin too.

If we are keeping the dedicated row, I don't think it provides any value without the link anyway...

--

+1, agree that we should think of a process to have visibility when adding new core-plugins (though, before that, I think we should have a philosophical debate _what_ are core-plugins 😂).

2020-10-05 18:14 UTC, rstavchansky commented
I'm noting here that @klavavej caught this showing up in the UI for Edge Handlers and requested that I add it to the docs. It's on the [Site Deploys Overview](https://deploy-preview-723--docs.netlify.app/site-deploys/overview/#deploy-summary) page. I'll need to update the docs if/when we remove it.

2020-10-06 14:43 UTC, nasivuela commented
Closing in favor of https://github.com/netlify/netlify-plugin-edge-handlers/issues/95 and UI + core plugins work.

2020-10-06 14:43 UTC, closed without merging